version: "3.7"

services:
  nginx:
    image: coming-soon/nginx:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: nginx
    restart: always
    expose:
      - 80
      - 443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-releases-backend.rule=Host(`fichtme.nl`)"
      - "traefik.http.routers.dev-releases-backend.entrypoints=websecure"
      - "traefik.http.routers.dev-releases-backend.tls.certresolver=fichtme-resolver"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: "traefik"
